# Script mode (cmake -P): embeds compiled SPIR-V blobs into a C++ source file.
# Inputs: MANIFEST (lines of "<name>|<stage>|<entry>|<spv path>"), OUTPUT (generated .cpp path).

if(NOT MANIFEST OR NOT OUTPUT)
    message(FATAL_ERROR "StradaEmbedShaders.cmake requires MANIFEST and OUTPUT")
endif()

file(STRINGS "${MANIFEST}" entries)

set(blobDefinitions "")
set(tableEntries "")
set(index 0)
foreach(entry IN LISTS entries)
    if(entry STREQUAL "")
        continue()
    endif()
    string(REPLACE "|" ";" fields "${entry}")
    list(GET fields 0 name)
    list(GET fields 1 stage)
    list(GET fields 2 entryPoint)
    list(GET fields 3 path)

    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hexLength)
    math(EXPR byteCount "${hexLength} / 2")
    if(byteCount EQUAL 0)
        message(FATAL_ERROR "Shader blob '${path}' is empty")
    endif()

    # Emit 0xNN bytes, 24 per line (CMake regular expressions have no {n} quantifier, so the row pattern is spelled out).
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REPEAT "0x[0-9a-f][0-9a-f]," 24 rowPattern)
    string(REGEX REPLACE "(${rowPattern})" "\\1\n\t\t\t" bytes "${bytes}")

    if(stage STREQUAL "vertex")
        set(stageEnum "ShaderStage::Vertex")
    elseif(stage STREQUAL "pixel")
        set(stageEnum "ShaderStage::Pixel")
    else()
        set(stageEnum "ShaderStage::Compute")
    endif()

    string(APPEND blobDefinitions "\t\talignas(4) uint8_t const s_Blob${index}[] = {\n\t\t\t${bytes}\n\t\t};\n\n")
    string(APPEND tableEntries "\t\t{ \"${name}\", ${stageEnum}, \"${entryPoint}\", s_Blob${index}, ${byteCount} },\n")
    math(EXPR index "${index} + 1")
endforeach()

set(content "// Generated by cmake/StradaEmbedShaders.cmake. Do not edit.

#include \"Strada/RHI/EmbeddedShaders.h\"

#include <cstdint>

namespace Strada
{
	namespace
	{
${blobDefinitions}		EmbeddedShader const s_Shaders[] = {
${tableEntries}		};
	}

	std::span<EmbeddedShader const> GetEmbeddedShaders()
	{
		return s_Shaders;
	}
}
")

# Only touch the file when its content changes, so dependent objects are not rebuilt needlessly.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
