# Script mode (cmake -P): embeds binary files into a C++ source file implementing Strada/Core/EmbeddedResources.h.
# Inputs: MANIFEST (lines of "<name>|<file path>"), OUTPUT (generated .cpp path).

if(NOT MANIFEST OR NOT OUTPUT)
    message(FATAL_ERROR "StradaEmbedResources.cmake requires MANIFEST and OUTPUT")
endif()

file(STRINGS "${MANIFEST}" entries)

set(dataDefinitions "")
set(tableEntries "")
set(index 0)
foreach(entry IN LISTS entries)
    if(entry STREQUAL "")
        continue()
    endif()
    string(FIND "${entry}" "|" separator)
    string(SUBSTRING "${entry}" 0 ${separator} name)
    math(EXPR pathStart "${separator} + 1")
    string(SUBSTRING "${entry}" ${pathStart} -1 path)

    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hexLength)
    math(EXPR byteCount "${hexLength} / 2")
    if(byteCount EQUAL 0)
        message(FATAL_ERROR "Resource '${path}' is empty")
    endif()

    # Emit 0xNN bytes, 24 per line (CMake regular expressions have no {n} quantifier, so the row pattern is spelled out).
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REPEAT "0x[0-9a-f][0-9a-f]," 24 rowPattern)
    string(REGEX REPLACE "(${rowPattern})" "\\1\n\t\t\t" bytes "${bytes}")

    string(APPEND dataDefinitions "\t\talignas(16) uint8_t const s_Data${index}[] = {\n\t\t\t${bytes}\n\t\t};\n\n")
    string(APPEND tableEntries "\t\t\t{\"${name}\", s_Data${index}, ${byteCount}},\n")
    math(EXPR index "${index} + 1")
endforeach()

if(index EQUAL 0)
    set(lookup "\t\t(void)name;\n\t\treturn {};\n")
    set(table "")
else()
    set(lookup "\t\tfor (Resource const& resource : s_Resources)
		{
			if (resource.Name == name)
			{
				return std::span<uint8_t const>(resource.Data, resource.Size);
			}
		}
		return {};
")
    set(table "\t\tstruct Resource
		{
			std::string_view Name;
			uint8_t const* Data;
			size_t Size;
		};

${dataDefinitions}\t\tResource const s_Resources[] = {
${tableEntries}\t\t};
")
endif()

set(content "// Generated by cmake/StradaEmbedResources.cmake. Do not edit.

#include \"Strada/Core/EmbeddedResources.h\"

#include <cstddef>
#include <cstdint>

namespace Strada
{
	namespace
	{
${table}	}

	std::span<uint8_t const> EmbeddedResources::Get(std::string_view name)
	{
${lookup}	}
}
")

# Only touch the file when its content changes, so dependent objects are not rebuilt needlessly.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
